CREATE TABLE IF NOT EXISTS Users (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
    apartmentNumber VARCHAR(45) NOT NULL,
    email VARCHAR(45) NOT NULL,
    phonenumber VARCHAR(45) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    UNIQUE (apartmentNumber),
    UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS Booking (
id INT PRIMARY KEY AUTO_INCREMENT,
userId INT NOT NULL,
date DATE NOT NULL,
timeslot VARCHAR(50) NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users(id)
    );
